spring:
  application:
    name: eureka-server
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

# server:
#   port: 9102
