spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: produits 
          uri: lb://MICROSERVICE-PRODUITS
          predicates:
          - Path=/produits/**
        - id: paiement
          uri: lb://MICROSERVICE-PAIEMENT
          predicates:
          - Path=/paiement/**
        - id: commandes
          uri: lb://MICROSERVICE-COMMANDES
          predicates:
          - Path=/commandes/** 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway

server:
  port: 9103
