spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: products
          uri: lb://MICROSERVICE-PRODUCTS
          predicates:
          - Path=/products/**
        - id: paiement
          uri: lb://MICROSERVICE-PAIEMENT
          predicates:
          - Path=/paiement/**
        - id: commandes
          uri: lb://MICROSERVICE-COMMANDES
          predicates:
          - Path=/commandes/**
        - id: shipping
          uri: lb://MICROSERVICE-SHIPPING
          predicates:
            - Path=/shippings/**
  security:
    user:
      name: utilisateur
      password: pswd
  config:
    import: optional:configserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway

server:
  port: 9103
