spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: products
          uri: lb://MICROSERVICE-PRODUCTS
          predicates:
          - Path=/products/**
          filters:
          - AddRequestHeader=Authorization, "Bearer {token}"
        - id: paiement
          uri: lb://MICROSERVICE-PAIEMENTS
          predicates:
          - Path=/paiement/**
        - id: commandes
          uri: lb://MICROSERVICE-COMMANDES
          predicates:
          - Path=/commandes/**
        - id: shipping
          uri: lb://MICROSERVICE-SHIPPINGS
          predicates:
            - Path=/shippings/**
        - id: security1
          uri: lb://MICROSERVICE-SECURITY
          predicates:
            - Path=/auth/**
            
  security:
    user:
      name: utilisateur
      password: pswd
  config:
    import: optional:configserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway

   zipkin:
     baseUrl: http://localhost:9411

server:
  port: 9102
