spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: 
          uri: lb://MICROSERVICE-PRODUITS
          predicates:
          - Path=/produits/**
        - id:
          uri: lb://MICROSERVICE-PAIEMENT
          predicates:
          - Path=/paiement/**
        -id:
          uri: lb://MICROSERVICE-COMMANDES
          predicates:
          - Path=/commandes/** 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

server:
  port: 9103
