spring:
  application:
    name: microservice-clientui
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    serviceUrl:
      # http://<eureka-server_ip-addr>:<port>/eureka/
      defaultZone: http://localhost:9102/eureka/


