spring:
  application:
    name: microservice-clientui
  cloud:
    config:
      uri: http://localhost: 9101

eureka:
  client:
    registryWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

microservice-produits:
  ribbon:
    listOfServers: localhost:9001,localhost:9011
