spring:
  application:
    name: microservice-clientui
  cloud:
    loadbalancer:
      ribbon:
        enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

microservice-produits:
  ribbon:
    listOfServers: localhost:9001,localhost:9011


