spring:
  application:
    name: microservice-clientui
  cloud:
    discovery:
      reactive:
        enabled: false
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      # http://<eureka-server_ip-addr>:<port>/eureka/
      defaultZone: http://localhost:8761/eureka/

  zipkin:
    baseUrl: http://localhost:9411

server:
  port: 8080

