spring:
  application:
    name: microservice-clientui-shipping
  cloud:
    discovery:
      reactive:
        enabled: false
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      # http://<eureka-server_ip-addr>:<port>/eureka/
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
