spring:
  application:
    name: microservice-security
  cloud:
    discovery:
      reactive:
        enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.he.Driver
    username: sa
    password:
    databasePlatform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      # http://<eureka-server_ip-addr>:<port>/eureka/
      defaultZone: http://localhost:8761/eureka/

  zipkin:
    baseUrl: http://localhost:9411

server:
  port: 8081
