spring:
  application:
    name: microservice-paiement
    
  datasource:
    database: microservice_paiement
    hostname: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    username: ${POSTGRES_USER:khoffy}
    password: ${POSTGRES_PASSWD:SwaY890}
    url: jdbc:postgresql://${spring.datasource.hostname}:${spring.datasource.port}/${spring.datasource.database}
  initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

server:
    port: 9003

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
